name = "PartitionedVectors"
uuid = "9d5e22db-ddc8-46c9-8309-91b035e7f733"
authors = ["Paul Raynaud <paul.raynaud@polymtl.ca>"]
version = "0.1.2"

[deps]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
PartitionedStructures = "a6683cb1-4e99-4d03-b5b5-b79ed0acabcf"

[compat]
Krylov = "=0.9.0"
LinearOperators = "2.4.0"
PartitionedStructures = "0.1.4, 0.1.5"
julia = "^1.6.0"

[extras]
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
PartitionedStructures = "a6683cb1-4e99-4d03-b5b5-b79ed0acabcf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra", "StatsBase", "Krylov", "LinearOperators"]
